import { SessionReport } from "../src/report/types";

export function buildReportFixture(overrides: Partial<SessionReport> = {}): SessionReport {
    return {
        sessionIds: ["session-test"],
        files: ["C:\\telemetry\\session-test.jsonl"],
        totalEvents: 100,
        analysisScope: "full",
        tailLines: null,
        strategy: "trade_5x",
        mode: "PAPER",
        startBalance: 100,
        buys: 0,
        sells: 0,
        rejectionCount: 0,
        fallbackCount: 0,
        momEventCount: 0,
        mcEventCount: 0,
        shadowEventCount: 0,
        shadowResolvedEventCount: 0,
        shadowUnresolvedEventCount: 0,
        shadowWinCount: 0,
        netPnl: 0,
        grossPnl: 0,
        totalFees: 0,
        shadowWinRate: 0,
        shadowTotalHypothetical: 0,
        rttAvg: 0,
        rttMax: 0,
        rttP95: 0,
        feedWindows: [],
        mcConvAvg: 0,
        mcConvMin: 0,
        mcConvMax: 0,
        mcBelow062: 0,
        mcBelow068: 0,
        momDirections: {},
        momScoreMin: 0,
        momScoreMax: 0,
        momConfAvg: 0,
        momUsableEventCount: 0,
        momMissingFieldEventCount: 0,
        trades: [],
        rejectionBreakdown: [],
        rejectionPayloads: {},
        anomalies: [],
        gateChecks: [],
        ...overrides,
    };
}
